export {default as Navbar} from './Navbar'
export {default as News} from './News'
export {default as HomePage } from './HomePage'
export {default as Exchange} from './Exchanges'
export {default as CryptoDetails} from './CryptoDetails'
export {default as CrytoCurrencies} from './CrytoCurrencies'